soc: qcom: glink: Fix broken list usage in debugfs functions
Although glink_xprt_ctx_iterator_init() is only used in debugfs code
that's only relevant to some people inside Qualcomm, let's fix it up to
resolve a new warning from GCC.

This fixes the following warning:
In file included from include/asm-generic/bug.h:13,
                 from arch/arm64/include/asm/bug.h:67,
                 from include/linux/bug.h:4,
                 from arch/arm64/include/asm/arch_timer.h:25,
                 from drivers/soc/qcom/glink.c:12:
drivers/soc/qcom/glink.c: In function 'glink_xprt_ctx_iterator_init':
include/linux/kernel.h:820:3: error: array subscript -3 is outside array bounds of 'struct list_head[1]' [-Werror=array-bounds]
  820 |  ((type *)(__mptr - offsetof(type, member))); })
      |  ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
include/linux/list.h:352:2: note: in expansion of macro 'container_of'
  352 |  container_of(ptr, type, member)
      |  ^~~~~~~~~~~~
drivers/soc/qcom/glink.c:5822:19: note: in expansion of macro 'list_entry'
 5822 |  xprt_i->i_curr = list_entry(&transport_list,
      |                   ^~~~~~~~~~
In file included from include/linux/preempt.h:10,
                 from include/linux/spinlock.h:50,
                 from include/linux/seqlock.h:35,
                 from include/linux/time.h:5,
                 from include/uapi/linux/timex.h:56,
                 from include/linux/timex.h:56,
                 from include/linux/sched.h:19,
                 from include/linux/kthread.h:5,
                 from drivers/soc/qcom/glink.c:15:
drivers/soc/qcom/glink.c:330:18: note: while referencing 'transport_list'
  330 | static LIST_HEAD(transport_list);
      |                  ^~~~~~~~~~~~~~
include/linux/list.h:23:19: note: in definition of macro 'LIST_HEAD'
   23 |  struct list_head name = LIST_HEAD_INIT(name)
      |                   ^~~~

Signed-off-by: Sultan Alsawaf <sultan@kerneltoast.com>